config/routes.rb
Rails.application.routes.draw do
  
  get '/stores', to: 'stores#index', as: 'stores' 
  get '/stores/new', to: 'stores#new', as: 'new_store'
  post '/stores', to: 'stores#create'
  get '/stores/stores_search', to: 'stores#store_search', as: 'store_search'
  get '/stores/inventory', to: 'stores#inventory', as: 'inventory'
  get '/stores/inventory_search', to: 'stores#inventory_search', as: 'inventory_search'
  get '/stores/:id', to: 'stores#show', as: 'store'
  

  get '/drinks', to: 'drinks#index', as: 'drinks' 
  get '/drinks/new', to: 'drinks#new', as: 'new_drink'
  post '/drinks', to: 'drinks#create'
  get '/drinks/drinks_search', to: 'drinks#drink_search', as: 'drink_search'
  get '/drinks/beers', to: 'drinks#beers', as: 'beers'
  get '/drinks/beer_search', to: 'drinks#beer_search', as: 'beer_search'
  get '/drinks/wines', to: 'drinks#wines', as: 'wines'
  get '/drinks/wines_search', to: 'drinks#wine_search', as: 'wine_search'
  get '/drinks/liquors', to: 'drinks#liquors', as: 'liquors'
  get '/drinks/liquors_search', to: 'drinks#liquor_search', as: 'liquor_search'
  get '/drinks/:id', to: 'drinks#show', as: 'drink'
  

  post '/store_drinks', to: 'store_drinks#create', as: 'create_store_drink'
  get '/store_drinks/:id/delete', to: 'store_drinks#delete', as: 'delete_store_drink'

  get '/', to: 'application#root', as: 'root'
  get '/home', to: 'application#home', as: 'home'

  resources :users, only: [:new, :show, :create]
  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/sessions', to: 'sessions#delete'

  get '/users/create_store/:id', to: 'users#create_store', as: 'create_store'
  post '/users/add_store', to: 'users#add_store', as: 'add_store'
  
end

app/models/store.rb
class Store < ApplicationRecord
    has_many :store_drinks
    has_many :drinks, through: :storedrinks 
    belongs_to :user
    validates :name, presence: true, uniqueness: true
    validates :location, presence: true

    def store_drinks
        StoreDrink.all.select do |sd|
           sd.store_id == self.id
        end
    end

    def self.store_search(params)
        self.where('name LIKE ?', "%#{params[:name]}%")
    end

    def self.your_stores(user)
        Store.all.select do |store|
            store.user_id == user
        end
    end

    def self.inventory_search(params)
        self.where('name LIKE ? AND user_id = ?', "%#{params[:name]}%", "#{params[:user_id]}")
    end

    def api
        client = GoogleSearchResults.new(q:"#{self.name} liqour", tbm:"isch", serp_api_key: "e35522f2e24cc87ff79ad525763b1e0ed3983f19c268a2750c65eb7f1444d1d6")
        hash_results = client.get_hash
        self.update(image: hash_results[:images_results][0][:thumbnail])
    end

    def self.api     
        Store.all.each do |store|
            client = GoogleSearchResults.new(q:"#{store.name} liqour", tbm:"isch", serp_api_key: "e35522f2e24cc87ff79ad525763b1e0ed3983f19c268a2750c65eb7f1444d1d6")
            hash_results = client.get_hash
            store.update(image: hash_results[:images_results][0][:thumbnail])

        end
    end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
    
    def index
        @stores = Store.all
    end

    def new
        @store = Store.new
    end

    def create
        @store = Store.new(store_params) 
        @store.update(user_id: session[:user_id])
        @store.api 
        if @store.save
            redirect_to store_path(@store)
        else 
            flash[:errors] = @store.errors.full_messages
            render :new
        end
    end

    def show
        @store = Store.find(params[:id])
        @store_drinks = @store.store_drinks
        @store_drink = StoreDrink.new
        @drinks = Drink.all.sort{ |a, b| a.name <=> b.name }
       
        @drink = Drink.new 
        
    end

    def store_search
        @search_results = Store.store_search(search_params)
        render :store_search_results
    end

    def inventory
        @stores = Store.your_stores(session[:user_id])
    end

    def inventory_search 
        @search_results = Store.inventory_search(inventory_search_params)
        render :inventory_search_results
    end 

    private

    def store_params
        params.require(:store).permit(:name, :location)
    end

    def search_params
        params.permit(:name)
    end

    def inventory_search_params
        params.permit(:name, :user_id)
    end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_inventory_option.html.erb
<div class= "show">
<% if !@store_drinks.empty? %>
    <% @store_drinks.each do |sd| %>
        <p>Brand: <%= sd.drink.name %></p>
        <p>Price: <%= sd.drink.price %></p>
        <%= link_to "Delete drink", delete_store_drink_path(StoreDrink.find_by(drink_id: sd.drink, store_id: @store.id)) %>
        <hr>
        <br>
    <% end %>
<% else %>
    <%= "#{@store.name} has no inventory" %>
    <br>
<% end %>
<br>

    <%= form_with model: @store_drink, :url => create_store_drink_path, method: :post do |f| %>
        <%= f.collection_select :drink_id, @drinks, :id, :name %>
        <%= f.hidden_field :store_id, :value => @store.id%>
        <%= f.submit "Add Drink to Inventory"%>  

<% end %>
</div>

app/views/stores/index.html.erb
<%= render 'application/nav_bar' %>
<br>

<%= form_with url: store_search_path, method: :get, local:true do %>
    <div style= "color: white; font-family: 'Kaushan Script', cursive; font-size: 1.3em;"><p>Search stores: <%= text_field_tag(:name, params[:search]) %></p></div>
    <div style= "font-family: 'Kaushan Script', cursive;"><%= submit_tag "Search" %></div>
    <% end %>
    <br>


<div class="card-container">
    <% @stores.each do |s| %>

  <div class="card" style="width: 18rem; display: inline-block; background-image: url(<%=s.image%>);">
    <div class="card-body">
      <h5 class="card-title"><%=link_to s.name, store_path(s)%></h5> 
    </div>
  </div>

   <% end %>
</div>
  
</div>

app/views/stores/inventory.html.erb
<%= render 'application/nav_bar' %>
<div class= "show">
<br>
<h1>Your Stores</h1>

<%= form_with url: inventory_search_path, method: :get, local:true do %>
    <p>Search your stores: <%= text_field_tag(:name, params[:search]) %></p>
    <%= hidden_field_tag :user_id, session[:user_id] %>
    <%= submit_tag "Search" %>
    <% end %>
    <br>
<div style= "color: white; border-top: solid white 2px;"></div>
<br>
<%= link_to "Add a store", new_store_path %>


<hr>

<div class="card-container">
    <% @stores.each do |s| %>

  <div class="card" style="width: 18rem; display: inline-block; background-image: url(<%=s.image%>);">
    <div class="card-body">
      <h5 class="card-title"><%=link_to s.name, store_path(s)%></h5> 
    </div>
  </div>

   <% end %>
</div>
  
</div>



</div>

app/views/stores/inventory_search_results.html.erb
<div class= "show">
<%= render 'application/nav_bar' %>
<h1>Your stores</h1>

<%= form_with url: inventory_search_path, method: :get, local:true do %>
    <p>Search stores: <%= text_field_tag(:name, params[:search]) %></p>
    <%= hidden_field_tag :user_id, session[:user_id] %>
    <%= submit_tag "Search" %>
    <% end %>
    <br>
    
<strong> Results: </strong>
<br>
<br>

<% @search_results.each do |result| %>
    <%= link_to result.name, store_path(result) %>
    <br>
    <% end %>
</div>

app/views/stores/new.html.erb
<%= render 'application/nav_bar' %>
<div style= "color:white; font-family: 'Kaushan Script', cursive;" ><h1>Create a new store!</h1></div>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <%= error %>
        <br>
        <% end %>
        <br>
<% end %>

<div><%= form_for @store do |f| %>
 <div style= "color:white; font-family: 'Kaushan Script', cursive;" ><%= f.label :name %></div>
 <%= f.text_field :name %>
 <br>
 <div style= "color:white; font-family: 'Kaushan Script', cursive;" ><%= f.label :location %></div>
 <%= f.text_field :location %>
 <br>
 <div style= "color:white; font-family: 'Kaushan Script', cursive;" ><%= f.submit "Add store" %>
 <br>
<% end %></div>
<br>
<div>

app/views/stores/show.html.erb
<%= render 'application/nav_bar' %>
<div class= "show">

<br>
<br>
<div style= "color: white"><h2><%= @store.name %>'s inventory </h2></div>

<br>

<% if session[:user_id] == @store.user_id %>
    <%= render 'inventory_option' %>
<% else %>
    <% if !@store_drinks.empty? %>
        <% @store_drinks.each do |sd| %>
          <div style= "color: white; border-top: solid white 2px;"></div>
            <div style= "color: white"><p>Brand: <%= sd.drink.name %></p></div>
            <div style= "color: white"><p>Price: $<%= sd.drink.price %></p></div>
            <hr>
           
        <% end %>
    <% else %>
        <div style= "color: white"><%= "#{@store.name} has no inventory" %></div>
        <br>
    <% end %>
<% end %>

<br>
<div style= "color: white"><%= link_to "Back to stores", stores_path %></div>

</div>

app/views/stores/store_search_results.html.erb
<%= render 'application/nav_bar' %>
<h1>Stores</h1>

<%= form_with url: store_search_path, method: :get, local:true do %>
    <p>Search stores: <%= text_field_tag(:name, params[:search]) %></p>
    <%= submit_tag "Search" %>
    <% end %>
    <br>
    
<strong> Results: </strong>
<br>
<br>

    <div class="card-container">
    <% @search_results.each do |result| %>

  <div class="card" style="width: 18rem; display: inline-block; background-image: url(<%=result.image%>);">
    <div class="card-body">
      <h5 class="card-title"><%= link_to result.name, store_path(result) %></h5> 
    </div>
  </div>

   <% end %>
</div>
  
</div>