config/routes.rb
Rails.application.routes.draw do
  
  get '/stores', to: 'stores#index', as: 'stores' 
  get '/stores/new', to: 'stores#new', as: 'new_store'
  post '/stores', to: 'stores#create'
  get '/stores/stores_search', to: 'stores#store_search', as: 'store_search'
  get '/stores/inventory', to: 'stores#inventory', as: 'inventory'
  get '/stores/inventory_search', to: 'stores#inventory_search', as: 'inventory_search'
  get '/stores/:id', to: 'stores#show', as: 'store'
  

  get '/drinks', to: 'drinks#index', as: 'drinks' 
  get '/drinks/new', to: 'drinks#new', as: 'new_drink'
  post '/drinks', to: 'drinks#create'
  get '/drinks/drinks_search', to: 'drinks#drink_search', as: 'drink_search'
  get '/drinks/beers', to: 'drinks#beers', as: 'beers'
  get '/drinks/beer_search', to: 'drinks#beer_search', as: 'beer_search'
  get '/drinks/wines', to: 'drinks#wines', as: 'wines'
  get '/drinks/wines_search', to: 'drinks#wine_search', as: 'wine_search'
  get '/drinks/liquors', to: 'drinks#liquors', as: 'liquors'
  get '/drinks/liquors_search', to: 'drinks#liquor_search', as: 'liquor_search'
  get '/drinks/:id', to: 'drinks#show', as: 'drink'
  

  post '/store_drinks', to: 'store_drinks#create', as: 'create_store_drink'
  get '/store_drinks/:id/delete', to: 'store_drinks#delete', as: 'delete_store_drink'

  get '/', to: 'application#root', as: 'root'
  get '/home', to: 'application#home', as: 'home'

  resources :users, only: [:new, :show, :create]
  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/sessions', to: 'sessions#delete'

  get '/users/create_store/:id', to: 'users#create_store', as: 'create_store'
  post '/users/add_store', to: 'users#add_store', as: 'add_store'
  
end

app/models/drink.rb
require 'google_search_results'
class Drink < ApplicationRecord
    has_many :storedrinks
    has_many :stores, through: :storedrink
    validates :name, uniqueness: true, presence:true
    validates :price, presence: true

    def self.beers
        Drink.all.select do |drink|
            drink.category == "BEER"
        end.sort
    end

    def self.wines
        Drink.all.select do |drink|
            drink.category == "WINE"
        end
    end

    def self.liquors
        Drink.all.select do |drink|
            drink.category == "LIQUOR"
        end
    end

    def self.beer_search(params)
        self.where('name LIKE ? AND category = "BEER"', "%#{params[:name]}%")
    end

    def self.liquor_search(params)
        self.where('name LIKE ? AND category = "LIQUOR"', "%#{params[:name]}%")
    end

    def self.wine_search(params)
        self.where('name LIKE ? AND category = "WINE"', "%#{params[:name]}%")
    end

    def self.drink_search(params)
        self.where('name LIKE ?', "%#{params[:name]}%")
    end

    def stores
       @sd= StoreDrink.all.select do |sd|
            sd.drink == self   
       end
       @sd.map do |sd|
        sd.store
       end
    end

    def api
        client = GoogleSearchResults.new(q:"#{self.name} liquor", tbm:"isch", serp_api_key: "e35522f2e24cc87ff79ad525763b1e0ed3983f19c268a2750c65eb7f1444d1d6")
        hash_results = client.get_hash
        self.update(image: hash_results[:images_results][0][:thumbnail])
    end


    def self.api     
        Drink.all.each do |drink|
            client = GoogleSearchResults.new(q:"#{drink.name}", tbm:"isch", serp_api_key: "e35522f2e24cc87ff79ad525763b1e0ed3983f19c268a2750c65eb7f1444d1d6")
            hash_results = client.get_hash
            drink.update(image: hash_results[:images_results][0][:thumbnail])

        end
    end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController

    def index
        @drinks = Drink.all.sort{ |a, b| a.name <=> b.name }
    end

    def new
        @drink = Drink.new
    end

    def create
        @drink = Drink.new(drink_params)
        if @drink.save
            redirect_to drink_path(@drink)
        else 
            flash[:errors] = @drink.errors.full_messages
            render :new
        end
    end

    def show 
        @drink = Drink.find(params[:id])
        @store_drink = StoreDrink.new
        if session[:user_id]
            @user = User.find(session[:user_id])
            @stores = @user.stores
        end
        
    end

    def beers
        @beers = Drink.beers.sort{ |a, b| a.name <=> b.name }
    end

    def wines
        @wines= Drink.wines.sort{ |a, b| a.name <=> b.name }
    end

    def liquors
        @liquors = Drink.liquors.sort{ |a, b| a.name <=> b.name }
    end

    def liquor_search
        @search_results = Drink.liquor_search(search_params)
        render :liquor_search_results
    end

    def beer_search
        @search_results = Drink.beer_search(search_params)
        render :beer_search_results
    end

    def wine_search
        @search_results = Drink.wine_search(search_params)
        render :wine_search_results
    end

    def drink_search
        @search_results = Drink.drink_search(search_params)
        render :drink_search_results
    end
    
    private
    def drink_params
        params.require(:drink).permit(:name, :price)
    end

    def search_params
        params.permit(:name)
    end


end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/views/drinks/beer_search_results.html.erb
<%= render 'application/nav_bar' %>

<<div style= "color: white"><h1>Beer here </h1></div>

<%= form_with url: beer_search_path, method: :get, local:true do %>
    <div style= "color: white"><p>Search beers: <%= text_field_tag(:name, params[:search]) %></p></div>
    <%= submit_tag "Search" %>
    <% end %>
    <br>

<div style= "color: white"><strong> Results: </strong></div>
<br>
<br>

<div class="card-container">
    <% @search_results.each do |result| %>

  <div class="card" style="width: 18rem; display: inline-block; background-image: url(<%=result.image%>);">
    <div class="card-body">
      <h5 class="card-title"> <%= link_to result.name, drink_path(result) %></h5> 
    </div>
  </div>

   <% end %>
</div>

app/views/drinks/beers.html.erb
<%= render 'application/nav_bar' %>

<br>

<%= form_with url: beer_search_path, method: :get, local:true do %>
      <div style= "color: white; font-family: 'Kaushan Script', cursive; font-size: 1.3em;"><p>Search beers: <%= text_field_tag(:name, params[:search]) %></p></div>
    <%= submit_tag "Search" %>
    <% end %>
    <br>
<div class="card-container">
    <% @beers.each do |s| %>

  <div class="card" style="width: 18rem; display: inline-block; background-image: url(<%=s.image%>);" >
    <div class="card-body">
      <h5 class="card-title"> <%=link_to s.name, drink_path(s)%></h5> 
    </div>
  </div>

   <% end %>
</div>
  
</div>

app/views/drinks/drink_search_results.html.erb
<%= render 'application/nav_bar' %>

<div style= "color: white"><h1>Drinks</h1></div>

<%= form_with url: drink_search_path, method: :get, local:true do %>
   <div style= "color: white"><p>Search drinks: <%= text_field_tag(:name, params[:search]) %></p></div>
    <%= submit_tag "Search" %>
    <% end %>
    <br>

<div style= "color: white"><strong> Results: </strong></div>
<br>
<br>


<div class="card-container">
    <% @search_results.each do |result| %>

  <div class="card" style="width: 18rem; display: inline-block; background-image: url(<%=result.image%>);">
    <div class="card-body">
      <h5 class="card-title"> <%= link_to result.name, drink_path(result) %></h5> 
    </div>
  </div>

   <% end %>
</div>

app/views/drinks/index.html.erb
<%= render 'application/nav_bar' %>

<h1>Drinks</h1>

<%= form_with url: drink_search_path, method: :get, local:true do %>
    <p>Search drinks: <%= text_field_tag(:name, params[:search]) %></p>
    <%= submit_tag "Search" %>
    <% end %>
    <br>

<hr>
<br>
<%= "All Drinks" %>
<br>
<hr>
<% @drinks.each do |s| %>
 <%=link_to s.name, drink_path(s)%>
 <br>
 <hr>
<% end %>

app/views/drinks/liquor_search_results.html.erb
<%= render 'application/nav_bar' %>

<div style= "color: white"><h1>Liquor here </h1></div>

<%= form_with url: liquor_search_path, method: :get, local:true do %>
    <div style= "color: white"><p>Search liquor: <%= text_field_tag(:name, params[:search]) %></p></div>
    <%= submit_tag "Search" %>
    <% end %>
    <br>

<div style= "color: white"><strong> Results: </strong></div>
<br>
<br>

<div class="card-container">
    <% @search_results.each do |result| %>

  <div class="card" style="width: 18rem; display: inline-block; background-image: url(<%=result.image%>);">
    <div class="card-body">
      <h5 class="card-title"> <%= link_to result.name, drink_path(result) %></h5> 
    </div>
  </div>

   <% end %>
</div>

app/views/drinks/liquors.html.erb
<%= render 'application/nav_bar' %>
<br>
<%= form_with url: liquor_search_path, method: :get, local:true do %>
    <div style= "color: white; font-family: 'Kaushan Script', cursive; font-size: 1.3em;"><p>Search liquors: <%= text_field_tag(:name, params[:search]) %></p></div>
    <%= submit_tag "Search" %>
    <% end %>
    <br>


<div class="card-container">
    <% @liquors.each do |s| %>

  <div class="card" style="width: 18rem; display: inline-block; background-image: url(<%=s.image%>);">
    <div class="card-body">
      <h5 class="card-title"><%=link_to s.name, drink_path(s)%></h5> 
    </div>
  </div>

   <% end %>
</div>
  
</div>

app/views/drinks/new.html.erb
<%= render 'application/nav_bar' %>

<h1>Create a new drink!</h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <%= error %>
        <br>
        <% end %>
        <br>
<% end %>

<div><%= form_for @drink do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>
 <br>
 <%= f.label :price %>
 <%= f.text_field :price %>
 <br>
 <%= f.submit %>
<% end %></div>
<br>
<div>

app/views/drinks/show.html.erb
<%= render 'application/nav_bar' %>

<div class= "show">
<div style= "color: white"><h1><%= @drink.name %> </h1></div>
<br>

    <div style= "color: white"><p>Brand: <%= @drink.name %></p></div>
    <div style= "color: white"><p>Price: $<%= @drink.price %></p></div>
    <div style= "color: white"><p>Description: <%= @drink.description %></p></div>
    <% if @drink.category == "BEER" %>
        <div style= "color: white"><p>Quantity: <%= @drink.quantity %> pack</p></div>
    <% end %>
    <br>
    <% if !@drink.stores.empty? %>
        <div style= "color: white; border-top: solid white 2px;"><p>Available at:</p></div>
        <% @drink.stores.each do |store| %>
            <div style= "color: white"><%= link_to "#{store.name}", store_path(store) %></div>
        <% end %>
    <% else %>
    <div style= "color: white"><p> Not available in stores near you </p></div>
    <% end %>
    <hr>
    
    <% if session[:user_id] %>
    <%= form_with model: @store_drink, :url => create_store_drink_path, method: :post do |f| %>
        <%= f.collection_select :store_id, @stores, :id, :name %>
        <%= f.hidden_field :drink_id, :value => @drink.id%>
        <div style= "color: white"><%= f.submit "Add Drink to Inventory"%></div>
        <% end %>
    <% end %>

    <br>
    <%= link_to "Back to home", home_path %>
</div>

app/views/drinks/wine_search_results.html.erb
<%= render 'application/nav_bar' %>

<div style= "color: white"><h1>Wine here </h1></div>

<%= form_with url: wine_search_path, method: :get, local:true do %>
    <div style= "color: white"><p>Search wines: <%= text_field_tag(:name, params[:search]) %></p></div>
    <%= submit_tag "Search" %>
    <% end %>
    <br>
    
<div style= "color: white"><strong> Results: </strong></div>
<br>
<br>


<div class="card-container">
    <% @search_results.each do |result| %>

  <div class="card" style="width: 18rem; display: inline-block; background-image: url(<%=result.image%>);">
    <div class="card-body">
      <h5 class="card-title"> <%= link_to result.name, drink_path(result) %></h5> 
    </div>
  </div>

   <% end %>
</div>

app/views/drinks/wines.html.erb
<%= render 'application/nav_bar' %>
<br>
<%= form_with url: wine_search_path, method: :get, local:true do %>
     <div style= "color: white; font-family: 'Kaushan Script', cursive; font-size: 1.3em;"><p>Search wines: <%= text_field_tag(:name, params[:search]) %></p></div>
    <%= submit_tag "Search" %>
    <% end %>
    <br>

<div class="card-container">
    <% @wines.each do |s| %>

  <div class="card" style="width: 18rem; display: inline-block; background-image: url(<%=s.image%>);">
    <div class="card-body">
      <h5 class="card-title"><%=link_to s.name, drink_path(s)%></h5> 
    </div>
  </div>

   <% end %>
</div>
  
</div>