config/routes.rb
Rails.application.routes.draw do
  
  get '/stores', to: 'stores#index', as: 'stores' 
  get '/stores/new', to: 'stores#new', as: 'new_store'
  post '/stores', to: 'stores#create'
  get '/stores/stores_search', to: 'stores#store_search', as: 'store_search'
  get '/stores/inventory', to: 'stores#inventory', as: 'inventory'
  get '/stores/inventory_search', to: 'stores#inventory_search', as: 'inventory_search'
  get '/stores/:id', to: 'stores#show', as: 'store'
  

  get '/drinks', to: 'drinks#index', as: 'drinks' 
  get '/drinks/new', to: 'drinks#new', as: 'new_drink'
  post '/drinks', to: 'drinks#create'
  get '/drinks/drinks_search', to: 'drinks#drink_search', as: 'drink_search'
  get '/drinks/beers', to: 'drinks#beers', as: 'beers'
  get '/drinks/beer_search', to: 'drinks#beer_search', as: 'beer_search'
  get '/drinks/wines', to: 'drinks#wines', as: 'wines'
  get '/drinks/wines_search', to: 'drinks#wine_search', as: 'wine_search'
  get '/drinks/liquors', to: 'drinks#liquors', as: 'liquors'
  get '/drinks/liquors_search', to: 'drinks#liquor_search', as: 'liquor_search'
  get '/drinks/:id', to: 'drinks#show', as: 'drink'
  

  post '/store_drinks', to: 'store_drinks#create', as: 'create_store_drink'
  get '/store_drinks/:id/delete', to: 'store_drinks#delete', as: 'delete_store_drink'

  get '/', to: 'application#root', as: 'root'
  get '/home', to: 'application#home', as: 'home'

  resources :users, only: [:new, :show, :create]
  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/sessions', to: 'sessions#delete'

  get '/users/create_store/:id', to: 'users#create_store', as: 'create_store'
  post '/users/add_store', to: 'users#add_store', as: 'add_store'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :loggedin?

    def root 
        @drinks = Drink.all.sort{ |a, b| a.name <=> b.name }
        redirect_to home_path
    end

    def home
      @drinks = Drink.all.sort{ |a, b| a.name <=> b.name }
    end

    def current_user
      if session[:user_id]
        User.find(session[:user_id])
        # session[:store_id] = Store.find_by(user_id: session[:user_id])
      end
    end

    def loggedin?
      
      !!current_user
    end

    def authorize
      redirect_to login_path unless loggedin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_nav_bar.html.erb
<% if loggedin? %>

<nav class="navbar navbar-expand-lg navbar-dark fixed-top" style = "background-color: rgb(145, 0, 0);font-family: 'Kaushan Script', cursive; opacity: 0.80;">
  <div class="container">
   <%= link_to "LQR", home_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <%= link_to "Home", home_path, class:"nav-link" %>
                <span class="sr-only">(current)</span>
              </a>
        </li>
        <li class="nav-item active">
          <%=link_to "Inventory", inventory_path, class:"nav-link"%>
        </li>
        <li class="nav-item active">
          <%=link_to "Stores", stores_path, class:"nav-link" %>
        </li>
           <li class="nav-item active">
         <%= link_to "Log out", sessions_path, method: :delete, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<% else %>
    
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" style = "background-color: rgb(145, 0, 0);font-family: 'Kaushan Script', cursive; opacity: 0.80;">
  <div class="container">
   <%= link_to "LQR", home_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <%= link_to "Home", home_path, class:"nav-link" %>
                <span class="sr-only">(current)</span>
              </a>
        </li>
        <li class="nav-item active">
          <%= link_to "Stores", stores_path, class:"nav-link"%>
        </li>
        <li class="nav-item active">
          <%= link_to "Beer", beers_path, class:"nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Wine", wines_path, class:"nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Liquor", liquors_path, class:"nav-link" %>
        </li>
           <li class="nav-item active">
         <%= link_to "Login", login_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<% end %>

app/views/application/_no_results.html.erb
<% if @search_results.empty? %>
<p style = "color: red"> No search results found</p>
<% end %>

app/views/application/home.html.erb
<%= render 'nav_bar' %>
<br>
<%= form_with url: drink_search_path, method: :get, local:true do %>
    <div style= "color:white; font-family: 'Kaushan Script', cursive; font-size: 1.3em;"><p>Search drinks: <%= text_field_tag(:name, params[:search]) %></p></div>
    <div style= "font-family: 'Kaushan Script', cursive;"><%= submit_tag "Search" %></div>
    <% end %>
    <br>

<hr>

<div class="card-container">
    <% @drinks.each do |s| %>
    <div class="card" style="width: 18rem; display: inline-block; background-image: url(<%=s.image%>);">
      <div class="card-body">
        <h5 class="card-title"><%=link_to s.name, drink_path(s)%></h5> 
      </div>
    </div>

   <% end %>
</div>
  
</div>